Add shared library MUI hook support
trailofbits/ManticoreUI pull request #59
Opened 2022-04-12 13:27 UTC by lordidiot

This PR implements a new feature that allows MUI users to add bndb files of shared libraries used by the binaries (i.e. libc) to the project. The MUI hooks from these external bndbs will be extracted and added when MUI solve is run. This allows us to have "multi-file" projects.

Summary of code changes:
- Refactor of hook management code to decouple code from directly managing session data 
- Additional command `MUI - Manage Shared Library BNDBs`
- Additional dialog that allows adding and deletion of shared library bndbs

2022-04-18 21:25 UTC, ekilmer requested changes
I love the refactor! Nice work!

I'm a bit concerned about the so-called "hacks" though. We should discuss them in more detail.

2022-04-18 21:25 UTC, ekilmer commented on mui/native_plugin.py
> +                m.subscribe = lambda x, y: None
This doesn't seem safe. I don't quite understand what `m.subscribe` has to do with adding more hooks (I haven't looked at that code in a while), but we should at least first check that `m.subscribe == None` and then save whatever `m.subscribe` was into a temporary variable that is restored at the end.

2022-04-18 21:25 UTC, ekilmer commented on mui/native_plugin.py
> +        m.hook(0)(lambda state: state)
I don't understand why this is needed

2022-04-19 03:06 UTC, lordidiot commented
Some explanations and considerations regarding the hacks.

## The problem:
Currently, the `RebaseHooksPlugin` determines the base address of the shared library during *runtime*. This means that we have to add our manticore hooks during runtime.

The `add_hook` routine of manticore requires a call to [`self.subscribe/m.subscribe`](https://github.com/trailofbits/manticore/blob/a16a01148bde965803cc3a2101bf4e03b0dfe340/manticore/native/manticore.py#L306). This is done to subscribe the `self._hook_callback` function to the `will_execute_instruction` event.

However, after we allow manticore to run, `m.subscribe` is set to None [here](https://github.com/trailofbits/manticore/blob/a16a01148bde965803cc3a2101bf4e03b0dfe340/manticore/core/manticore.py#L1129) to stop any further callbacks from being added (I'm not sure what's the reason for this).

## The current (hacky) solution:
Based on my understanding of the [`add_hook`](https://github.com/trailofbits/manticore/blob/a16a01148bde965803cc3a2101bf4e03b0dfe340/manticore/native/manticore.py#L244) function, this is how hooks are added:
1. `self._hooks[pc of hook].add(our hook func)`, add our hook to a dictionary member of manticore
2. subscribe `self._hook_callback` to the  `will_execute_instruction` event

`self._hook_callback` is responsible for calling the relevant hook callbacks whenever the right PC is hit.
Note that in this implementation the step 2, subscribing to the event, is actually redundant after the first hook has been added. Because any further subscription of the same function to the same event would not make any difference, so step 2 only needs to be done once per manticore instance for hooks to work. Further, step 2 is the step that is preventing us from adding hooks during runtime because `m.subscribe = None` at runtime.

To work around this, I did the following.
1. Before running manticore, add one dummy hook to ensure that `self._hook_callback` was subscribed at least once prior to running.
2. Set `m.subscribe` to a function that does nothing, so that it can be called without any errors.
3. Continue using `m.hook()/add_hook` as per usual to add hooks, this will add our hooks to the `m._hooks` dictionary, and try to call `m.subscribe` which is just a function that does nothing (no errors).
4. Set `m.subscribe` back to original None value to maintain original manticore object behaviour

## Alternatives
There is one alternative implementation that I considered.
1. Add our own `will_execute_instruction` callback in `RebaseHooksPlugin` that will handle dispatch to rebased hooks
    - This should work well generally, and less hacky
    - Downside: Little bit of redundant/copypasted code from manticore
    - Downside: I'm not very sure on how to do custom hooks with this implementation, because currently custom hooks just run any code from the user (which would call m.hook). If we wanted to use this approach, we have to intercept m.hook when running the user's custom code.
    - A short code explainer if the description is a bit confusing:
```py
class RebaseHooksPlugin(Plugin):
    ...
    def did_map_memory_callback(self, _state, addr, _size, _perms, filename, offset, _addr):
        """Rebases hooks from library to loaded base address"""
        ...
        for hook_addr in self.find:
            self.hooks_or_smth[(hook_addr + self.base)] = self.find_f
    ...

    def will_execute_instruction_callback(self, state, pc, instruction):
        if pc in self.hooks_or_smth:
            cb = self.hooks_or_smth[pc]
            cb(state)
        ...
```

2022-04-20 18:56 UTC, ekilmer commented on mui/native_plugin.py
> +        m.hook(0)(lambda state: state)
I read the explanation below and I now understand 👍

2022-04-20 18:59 UTC, ekilmer commented on mui/native_plugin.py
> +                m.subscribe = lambda x, y: None
I read the explanation below and I still think we should practice defensive programming to either check that `m.subscribe == None` before doing the reassignment or save the original value of `m.subscribe` into a temporary variable and restore the original value at the end.

2022-04-20 19:14 UTC, ekilmer approved these changes
After fixing the one comment this LGTM!

2022-04-21 02:59 UTC, merged